### ISSUE TITLE
add AssertUniqueElements

### ISSUE THREAD

**Issue by olsavmic** [shipmonk-rnd/input-mapper#38]
Similar to [`@UniqueElements`](https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/UniqueElements.html).

`#[AssertUniqueElements(comparator: ?callable)]`

Optional `comparator` param to allow comparison of objects by value.

**Comment by JanTvrdik** [comment]
@olsavmic Do you need support for objects? Or would support for scalars be enough?

**Comment by olsavmic** [comment]
Actually not, as all the object use cases I'm interested in are represented as enums or enum-like values (represented as singletons). Simple equality check by reference would be enough :)

**Comment by JanTvrdik** [comment]
resolved by https://github.com/shipmonk-rnd/input-mapper/pull/56
