### ISSUE TITLE
Add DateTime formats

### ISSUE THREAD

**Issue by repli2dev** [shipmonk-rnd/input-mapper#50]
Possible to customize the format when mapping?

Like `Y-m-d` can be obtained, but AFAIK it needs some custom typing.

**Comment by JanTvrdik** [comment]
If you want to customize format for a specific field, you use `#[MapDateTimeImmutable]` with `format` parameter.

```php
class Person
{
    public function __construct(
        #[MapDateTimeImmutable(format: 'Y-m-d')]
        public readonly DateTimeImmutable $birthDate,
    ) {}
}
```

If you want to customize the default format used when mapping `DateTimeImmutable`, can extend  `DefaultMapperCompilerFactory` or configure existing `DefaultMapperCompilerFactory` with `setMapperCompilerFactory` method.

**Comment by repli2dev** [comment]
Ok, sorry I probably mislooked when I checked this agains the code.
