### ISSUE TITLE
Support for case mapping

### ISSUE THREAD

**Issue by repli2dev** [shipmonk-rnd/input-mapper#58]
In realtime usage there is need for some case mapping as sometimes the api are in `lower_case` while the code base is desired to be in `camelCase`... or even on per item bases when some field is renamed and should work with the old/new codebase.

The global rename can be done by recursive traversing once more time, yet it is performantly unwise... The ad-hoc one field renaming is more complicated.

**Comment by JanTvrdik** [comment]
Do you have any suggestions what should the API look like?

**Comment by repli2dev** [comment]
Usage 1: on object level

```php
#[PropertyNameRemapping(from: NamingConvention::SNAKE_CASE)]
final readonly class FooBar {
  public function __construct(
    public string $fooFirst,
    public string $fooSecond,
  ) {}
}
```

Usage 2: on property level
```php
final readonly class FooBar {
  public function __construct(
    public string $fooFirst,
    #[Rename(from: 'bar_second')]
    public string $fooSecond,
  ) {}
}
```

The behaviour of the second IMHO should that it remaps properly from `bar_second` or `fooSecond` to allow legacy field migration.

I peeked into the code today, yet the code is quite dense to orient in right now. Anyway if the above approach is sane I could try a PL in upcoming weeks.

**Comment by olsavmic** [comment]
I'd prefer to go the property-level first (eg `#[JsonProperty]` from Jackson or `#[SerializedName]` from symfony) route first.

The legacy field migration can now be achieved in code by specifying the old pair of optional properties. I'd prefer not to mix the "rename" and "alias" functionality. IMO Jackson does it nicely :) (`@JsonAlias` for migration, `@JsonProperty` for default name).

Sidenote: I like the idea of requiring every property to have a clear mapping (name) defined - not something I'd want impose on everybody on the tool level, but I'd consider it as an addition to our internal coding rules.

**Comment by repli2dev** [comment]
@JanTvrdik 🎉 This is enough for now... in long term it would be at least nice to support this also with `alternativeKey` (`legacyKey`)... if I do not miss anything then migrating for example from `fooProp` to `barProp` (when both payloads can come) I would needed two optional fields with extra check in constructor.
