### ISSUE TITLE
Optional optional

### ISSUE THREAD

**Issue by repli2dev** [shipmonk-rnd/input-mapper#59]
While I get why the `Optional` is there in most cases it seems superfluous as I would argue that PHP world (but no JS) is quite not relying on distinguishing between `undefined` and `null`...

... so in our (Kiwi.com) attempt to use this the API would be complicated by the `Optional` which complicated obtaining data and also creates a small issue on serialization (to the queues) and also brings undesired to the domain level (Optional from other library).

Public readonly DTO approach:
```
final readonly class Foo {
  public function __construct(
    public int $id,
    /** @var Optional<string> */
    public Optional $optionalValue,
  ) {}
}
```

- Extract property did not help as the Input Mapper takes type from it
- What helped (but PHPStan does not like it) is to do `public Optional|String|null` while not declaring it in the PHPDocs.

What helps is to make it private and use getter to extract and fallback to the value.

-----

My naive proposal here is to support `string|null $optionalValue = null`, with that I explicitly declare value to be used in situation when the value is not provided. Alternatively by explicitly agreeing to that behaviour via PHP Attribute. Yes I will lose the distinction but as I think it is not relevant in most cases in PHP world.

**Comment by JanTvrdik** [comment]
> My naive proposal here is to support string|null $optionalValue = null, with that I explicitly declare value to be used in situation when the value is not provided

That does not work well, because when using promoted properties, you can only define default value for the parameters at the end (see https://3v4l.org/ENCkj).

> Alternatively by explicitly agreeing to that behaviour via PHP Attribute. Yes I will lose the distinction but as I think it is not relevant in most cases in PHP world.

Something like that should be possible. See https://github.com/shipmonk-rnd/input-mapper/pull/60 for initial implementation draft.

**Comment by repli2dev** [comment]
I see, the proposal seems great!
